In [1]:
import pandas as pd
import numpy as np
import json
import tensorflow as tf
from pymongo import MongoClient

%matplotlib inline

import chart_studio.plotly as py
import plotly.graph_objects as go
import tensorflow

import os

In [2]:
# import all of necessary databases that will be used to learn off of

client = MongoClient('localhost', 27017)
db = client['toboR_brain']
leon = db['Leon']
client.close()

In [3]:
with open('appos.json') as apo:
    huh = json.load(apo)
    
wuh = huh['appos']
wuh['''we'll'''] = 'we will'

with open('contractions.json', 'r') as contr:
    tnoc = json.load(contr)

In [4]:
def smrt():
    morty = list(leon.find({},{'_id':0, 'line':1}))
    ri = leon.distinct('name')
    ck = ' '.join(ri)
    rick = str()
    for y in morty:
        rick += y['line'] + ' \n'

    rick += ck
    jerry = rick.split(' ')
    beth = [x.replace('(', '').replace(')', '').replace('"', '').replace('"', '').replace(',', '').replace('.', '')\
            .replace('?', '').replace('!', '').replace('\ ', '').replace('/', '').replace('''''', '').replace('''' ''', '')\
            .replace(';', '').strip().lower() for x in jerry]
    for x in beth:
        try:
            beth[beth.index(x)] = wuh[x]
            next
        except:
            'KeyError'
            next
    return beth

In [5]:
def whoitb(lst):
    lmno = []
    for x in lst:
        n = leon.count_documents({'name':x})
        lmno.append({x:n})
    return lmno

In [6]:
nom = leon.distinct('name')
wrdsmrty = smrt()
famous = whoitb(nom)
fms_ppl = {}
for x in famous:
    fms_ppl.update(x)
type(fms_ppl), fms_ppl
peps = pd.DataFrame(fms_ppl.values(), index=fms_ppl.keys()).sort_values(by=0, ascending=False)

In [7]:
data = [go.Bar(y=peps[0], x=peps.index)]

In [8]:
dt = go.Figure(data)

In [9]:
print(dt)

Figure({
    'data': [{'type': 'bar',
              'x': array(['Rick', 'Morty', 'Beth', 'Jerry', 'Summer', 'Pickle Rick', 'Supernova',
                          'Cop Morty', 'All Ricks', 'Mr. Goldenfold', 'President', 'Cop Rick',
                          'Testicle Monster A', 'Principal Vagina', 'Cornvelious Daniel',
                          'Snuffles', 'Dr. Wong', 'Drunk Rick', 'Agency Director', 'Alan',
                          'Candidate Morty', 'Vance', 'Scary Terry', 'Jessica', 'All Mortys',
                          'Million Ants', 'Riq IV', 'Ice-T', 'Morty 2', 'All Summers',
                          'Campaign Manager Morty', 'Alien Doctor', 'Lizard Morty', 'Cromulon',
                          'Nathan', 'Slick', 'Brad', 'Young Rick', 'Glasses Morty', 'Rick J-22',
                          'Vet', 'Birdperson', 'Mrs. Pancakes', 'Announcer', 'Teacher Rick',
                          'Morty 1', 'Narrator', 'Summer 1'], dtype=object),
              'y': array([420, 347, 148, 132

In [10]:
def whchone(brry):
    ssns = brry.distinct('season')
    eps = [brry.find({'season':x}, {'_id':0}) for x in ssns]
    tre = []
    for x in eps:
        q = []
        for t in x:
            q.append(t)
            next
        tre.append(q)
        next
    return tre

In [12]:
# gathers all of the lines for the character and returns a list of the character's lines

def saywht(da_pep, da_lst):
    da_info = list(da_lst.find({'name':da_pep}))
    guds = [[x['index'], x['name'], x['line']] for x in da_info]
    return guds

saywht('Summer 1', leon)[0]

[656, 'Summer 1', 'What do you mean?']

In [13]:
# used to gather all of the lines preceeding all of the lines of the desired character
# and returns paired off lines with index, name and line

def scrpt(da_pep, da_lst):
    gitgud = saywht(da_pep, da_lst)
    dobttr = []
    for x in gitgud:
        q = leon.find_one({'index':(int(x[0])-1)})
        try:
            dobttr.append([[q['index'], q['name'], q['line']], x])
        except:
            'ValueError'
            dobttr.append([['None', 'None', 'None'], x])
    return dobttr

mny = scrpt('Morty', leon)
mny[0]

[[0, 'Rick', "Morty! You gotta come on. Jus'... you gotta come with me."],
 [1, 'Morty', 'What, Rick? What’s going on?']]

In [14]:
# gather all possible words (including names of characters) and put them into
# a single list and create a tokenizer

def roy(tknz):
    splf = str('')
    nchps = str('')
    for x in tknz:
        splf += x[0][1]+' '+x[0][2]
        nchps += x[1][1]+' '+x[1][2]
    splfnchps = splf+' '+nchps
    ftbl = splfnchps.split(' ')
    bcktocrpt = [x.replace('(', '').replace(')', '').replace('"', '').replace('"', '').replace(',', '').replace('.', '')\
        .replace('?', '').replace('!', '').replace('\ ', '').replace('/', '').replace('''''', '').replace('''' ''', '')\
        .replace(';', '').strip().lower() for x in ftbl]
    for z in bcktocrpt:
        try:
            bcktocrpt[bcktocrpt.index(z)] = wuh[z]
            next
        except:
            'KeyError'
            next
    return bcktocrpt

In [15]:
# unique words only 

def schmkl(twntyfv):
    lmno = roy(twntyfv)
    hijk = list(set(lmno))
    return hijk[1:]

In [16]:
p = roy(mny)
o = {x : p.count(x) for x in p}
pqr = pd.DataFrame(o.values(), index=o.keys())
stuv = pqr.sort_values(0, ascending=False)

In [17]:
# create a tokenzier

def gimme(yowrds):
    wrd = list(set(yowrds))
    meaning = tf.keras.preprocessing.text.Tokenizer(num_words=len(wrd), filters='!"#$%&()*+,-./:;<=>?@[\\]^_`{|}~\t\n'\
                                             , lower=True, char_level=False\
                                             , oov_token='<<IDK>>')
    meaning.fit_on_texts(yowrds)
    return meaning

In [18]:
gitgud = gimme(wrdsmrty)
wrdsmrty[0:3]

['morty', 'you', 'gotta']

In [19]:
mrty = scrpt('Morty', leon)

In [20]:
def clnit(lines):
    ftbl = splfnchps.split(' ')
    bcktocrpt = [x.replace('(', '').replace(')', '').replace('"', '').replace('"', '').replace(',', '').replace('.', '')\
        .replace('?', '').replace('!', '').replace('\ ', '').replace('/', '').replace('''''', '').replace('''' ''', '')\
        .replace(';', '').strip().lower() for x in ftbl]

In [758]:
# turns all of the lines and names into seqs
# returns a list with target line first followed by
# the character who spoke the preceeding line
# as well as the preceeding line

def matrx(red, blu):
    lmno = []
    for x in red:
        ox = [y.replace('(', '').replace(')', '').replace('"', '').replace('"', '').replace(',', '').replace('.', '')\
              .replace('?', '').replace('!', '').replace('\ ', '').replace('/', '').replace('''''', '').replace('''' ''', '')\
              .replace(';', '').strip().lower() for y in x[0][2].split(' ')]
        q = blu.texts_to_sequences(ox)
        xo = [w.replace('(', '').replace(')', '').replace('"', '').replace('"', '').replace(',', '').replace('.', '')\
              .replace('?', '').replace('!', '').replace('\ ', '').replace('/', '').replace('''''', '').replace('''' ''', '')\
              .replace(';', '').strip().lower() for w in x[1][1].split(' ')]
        qr = blu.texts_to_sequences(xo)
        xox = [z.replace('(', '').replace(')', '').replace('"', '').replace('"', '').replace(',', '').replace('.', '')\
              .replace('?', '').replace('!', '').replace('\ ', '').replace('/', '').replace('''''', '').replace('''' ''', '')\
              .replace(';', '').strip().lower() for z in x[1][2].split(' ')]
        st = blu.texts_to_sequences(xox)
        p = []
        o = []
        po = []
        for y in q:
            p += y
            next
        for z in qr:
            o += z
            next
        for w in st:
            po += w
            next
        uv = [po, p, o]
        lmno.append(uv)
    return lmno

def bbb(ur_list):
    datlyfe = [x[0] for x in ur_list]
    thang = [w[1] for w in ur_list]
    getswl = tf.keras.preprocessing.sequence.pad_sequences(datlyfe, maxlen=3695, dtype='int32', padding='post', value=(3695+53))
    dyl = tf.keras.preprocessing.sequence.pad_sequences(thang, maxlen=3695, dtype='int32', padding='post', value=(3695+53))
    legday = []
    for y, x in enumerate(getswl):
        legday.append([x, dyl[y]])
        next
    return legday

In [759]:
a = matrx(mrty, gitgud)
ba = bbb(a)

In [760]:
gitgud.sequences_to_texts(ba[0])[1].replace('<<IDK>>', ''), ba[0][1]

("morty you gotta come on jus' you gotta come with me                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   

In [727]:
wrds = tf.data.Dataset.from_tensor_slices(ba)

In [739]:
def thicc(twocs):
    twocs = twocs[1]+twocs[0]
    inpt = twocs[:3696]
    target = twocs[3969::]
    return inpt, target

In [740]:
for x in wrds.take(1):
    print(x)

tf.Tensor(
[[  16   25  436 ... 3748 3748 3748]
 [  14    2  211 ... 3748 3748 3748]], shape=(2, 3695), dtype=int32)


In [741]:
dataset = wrds.map(thicc)
for cv in dataset.take(1):
    print(cv)

(<tf.Tensor: shape=(3695,), dtype=int32, numpy=array([  30,   27,  647, ..., 7496, 7496, 7496])>, <tf.Tensor: shape=(0,), dtype=int32, numpy=array([], dtype=int32)>)


In [742]:
buff_size = len(list(wrdsmrty))
batch_size = 1

dataset = wrds.shuffle(buff_size)
# .batch(batch_size, drop_remainder=True)

In [743]:
for x in dataset.take(1):
    print(x)

tf.Tensor(
[[ 226    2   28 ... 3748 3748 3748]
 [1164  692 1903 ... 3748 3748 3748]], shape=(2, 3695), dtype=int32)


In [744]:
vocab_size = len(list(gitgud.word_index))
embed_dim = 64
rnn_units = 128

def build_model(vocab_size, embed_dim, rnn_units, batch_size):
    model = tf.keras.Sequential([\
                                 tf.keras.layers.Embedding(vocab_size, embed_dim,\
                                                           batch_input_shape=[batch_size, None]),\
                                 tf.keras.layers.GRU(rnn_units,\
                                                      activation='tanh',\
                                                     return_sequences=True,\
                                                     stateful=True,\
                                                     recurrent_initializer='glorot_uniform'),\
                                tf.keras.layers.Dense(vocab_size, activation='softmax'),\
                                ])
    return model

In [734]:
model = build_model(vocab_size, embed_dim, rnn_units, batch_size)
model.summary()

Model: "sequential_8"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
embedding_8 (Embedding)      (1, None, 64)             232128    
_________________________________________________________________
gru_8 (GRU)                  (1, None, 128)            74496     
_________________________________________________________________
dense_8 (Dense)              (1, None, 3627)           467883    
Total params: 774,507
Trainable params: 774,507
Non-trainable params: 0
_________________________________________________________________


In [735]:
def loss(nochkn, nodinna):
    return tf.keras.losses.sparse_categorical_crossentropy(nochkn, nodinna, from_logits=False, axis=-1)

In [736]:
model.compile(optimizer='adam', loss=loss)

In [737]:
# checkpoints saved
checkpoint_dir = 'LeonLikesTvShows'
# files' names
checkpoint_prefix = os.path.join(checkpoint_dir, "ckpt_{epoch}")

checkpoint_callback=tf.keras.callbacks.ModelCheckpoint(
    filepath=checkpoint_prefix,
    save_weights_only=True)

In [ ]:
history = model.fit(dataset, epochs=5, callbacks=[checkpoint_callback])